# Generated by Django 5.2.11 on 2026-04-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('planetary_computer', 'Planetary Computer')], default='planetary_computer', max_length=50)),
                ('scene_id', models.CharField(db_index=True, max_length=255)),
                ('acquisition_date', models.DateTimeField()),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='satellite/previews/%Y/%m/')),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_class', models.CharField(blank=True, max_length=32, null=True)),
                ('predicted_at', models.DateTimeField(blank=True, null=True)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('land_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='document_processor.landplot')),
            ],
            options={
                'ordering': ['-acquisition_date'],
                'constraints': [models.UniqueConstraint(fields=('land_plot', 'source', 'scene_id'), name='unique_satellite_image_per_scene')],
            },
        ),
    ]
