# Generated by Django 5.2.11 on 2026-04-15 10:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import document_processor.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document_processor.services.storage.source_document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('egrn', 'Выписка ЕГРН'), ('auction_protocol', 'Протокол торгов'), ('sale_contract', 'Договор купли-продажи'), ('rent_contract', 'Договор аренды'), ('unknown', 'Неизвестно')], default='unknown', max_length=32)),
                ('text_content', models.TextField(blank=True)),
                ('ocr_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processed', 'Обработан'), ('failed', 'Ошибка')], default='uploaded', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=50, unique=True)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('use_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('egrn_source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egrn_land_plots', to='document_processor.sourcedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_kind', models.CharField(choices=[('rent', 'Договор аренды'), ('sale', 'Договор купли-продажи'), ('other', 'Иной договор')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land_plots', models.ManyToManyField(blank=True, related_name='contracts', to='document_processor.landplot')),
                ('party_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_party_1', to='document_processor.party')),
                ('party_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_party_2', to='document_processor.party')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='document_processor.sourcedocument')),
            ],
        ),
    ]
