# Generated by Django 5.2.11 on 2026-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_sourcedocument_ocr_result_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landplot',
            name='use_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
