# Generated by Django 5.2.11 on 2026-03-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='source_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('egrn', 'Выписка ЕГРН'), ('auction_protocol', 'Протокол торгов'), ('sale_contract', 'Договор купли-продажи'), ('unknown', 'Неизвестно')], default='unknown', max_length=32)),
                ('text_content', models.TextField(blank=True)),
                ('ocr_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processed', 'Обработан'), ('failed', 'Ошибка')], default='uploaded', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='document_processor.sourcedocument'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='egrn_source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egrn_land_plots', to='document_processor.sourcedocument'),
        ),
    ]
