# Generated by Django 5.2.11 on 2026-03-08 21:41

import document_processor.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0003_sourcedocument_contract_source_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedocument',
            name='file',
            field=models.FileField(upload_to=document_processor.services.storage.source_document_upload_path),
        ),
    ]
